### ISSUE TITLE
Added dataLayer Builder w-Standard Ecommerce tpl File

### ISSUE THREAD

**Issue by Mikeulrich75** [sahava/GoogleTagManagerTemplates#27]
Simo,

I have added my datalayer builder w-standard ecommerce tml (zip) file as an issue as you have requested. Please review the template and let me know your thoughts, suggestions, and thank you for being a GTM super hero! :)

[dataLayer Builder w-Standard eCommerce.tpl.zip](https://github.com/sahava/GoogleTagManagerTemplates/files/3423052/dataLayer.Builder.w-Standard.eCommerce.tpl.zip)

**Comment by sahava** [comment]
https://github.com/sahava/GoogleTagManagerTemplates/pull/26
