### ISSUE TITLE
New Custom Template - dataLayer Builder + Enhanced Ecommerce

### ISSUE THREAD

**Issue by Mikeulrich75** [sahava/GoogleTagManagerTemplates#39]
Please review my next custom template and let me know your thoughts and suggestions for improvement. 
[dataLayer Builder + EE.zip](https://github.com/sahava/GoogleTagManagerTemplates/files/3556801/dataLayer.Builder.%2B.EE.zip)

**Comment by sahava** [comment]
No need to raise issues for pull requests.

This is covered in:

https://github.com/sahava/GoogleTagManagerTemplates/pull/38
