### ISSUE TITLE
Facebook Pixel (unofficial) template - Consent mechanism

### ISSUE THREAD

**Issue by jamesmacwhite** [sahava/GoogleTagManagerTemplates#40]
Hi,

Thanks for providing this GTM template library resource. I was looking into the unofficial Facebook Pixel template and perhaps migrating existing fbq related Custom HTML tags due the user friendly aspect.

One thing I was interested in understanding is implementing the consent mechanism Facebook have into the template setup:

- https://developers.facebook.com/docs/facebook-pixel/implementation/gdpr/

Currently, I have this implemented in the "All Pages" Facebook Pixel with the init code. I am currently using a lookup table on a specific cookie being present and that returning "allow" or "deny" depending on the condition.

However I was wondering what the best way to achieve this would be under the template setup? I can see `fbq('init', pixelId, initObj);` in the sandbox JavaScript of the template. Would the best to do create a field to hold a value or variable that would ultimately return "allow" or "deny". Could I then add something like before the init call:

```
fbq('consent', data.consent);
```

Into the existing code?

Thanks in advance!

**Comment by sahava** [comment]
Hi

Good point - I'll add the consent stuff to the template. I'm making some other changes as well so this will sit in nicely!

**Comment by sahava** [comment]
Fixed in https://github.com/sahava/GoogleTagManagerTemplates/pull/41

**Comment by jamesmacwhite** [comment]
Thanks for this!
